### ISSUE TITLE
Make sidebar and panel resizable

### ISSUE THREAD

**Issue by egoist** [egoist/demoboard#18]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/demoboard/issues/18)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#23 Resizable sidebar and panel](https://issuehunt.io/r/egoist/demoboard/pull/23)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/demoboard/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by bertomoore** [comment]
Hi, I'd like to work on this issue and get some clarification on what you had in mind. Were you picturing the sidebar/panel to be resizable after rendering or do you want to add a parameter to the component that defines the size before rendering?

**Comment by egoist** [comment]
@bertomoore Like how Storybook works, e.g. http://airbnb.io/react-dates You can drag the edge of sidebar and bottom panel to resize them.

**Comment by bertomoore** [comment]
Thank you for the example! I'll start working on this now.
