### ISSUE TITLE
Update document title properly

### ISSUE THREAD

**Issue by egoist** [egoist/demoboard#6]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/demoboard/issues/6)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#9 feat: update document title](https://issuehunt.io/r/egoist/demoboard/pull/9)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/demoboard/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by qti3e** [comment]
I'll give it a try :)
